# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

name: 'Build'

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout Code'
        uses: 'actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8' # v6

      - name: 'Set up bazel'
        uses: 'bazel-contrib/setup-bazel@43d7d5ceab59a307da44fc7585faa2a2fff4f88d' # 0.16.0
        with:
          bazelisk-cache: true
          disk-cache: true
          external-cache: true
          repository-cache: true

      - name: 'Build'
        run: 'bazel build //...'
      # N.B. no test targets exist, so bazel test would exit with error
