# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

name: 'License'

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout Code'
        uses: 'actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8' # v6

      - name: 'Set up Go'
        uses: 'actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff' # v5
        with:
          go-version: '1.24'
          cache: true

      - name: 'Check'
        run: 'go run github.com/google/addlicense@v1.1.1 -check -s=only .'
